apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codebases.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: Codebase
    listKind: CodebaseList
    plural: codebases
    singular: codebase
    shortNames:
      - cdbs
  scope: Namespaced
  version: v1alpha1