apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: businessapplications.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: BusinessApplication
    listKind: BusinessApplicationList
    plural: businessapplications
    singular: businessapplication
    shortNames:
      - app
  scope: Namespaced
  version: v1alpha1