global:
  edpName: ""
  platform: "openshift"
  database:
    host: edp-db
    name: edp-db
    port: 5432

name: reconciler
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: reconciler
  # if not defined then .Chart.AppVersion is used
  version:

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 32Mi
