global:
  edpName: ""
  platform: "openshift"
  database:
    host: edp-db
    name: edp-db
    port: 5432

name: reconciler
image:
  name: reconciler
  version: v2.4.0

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 32Mi
