global:
  edpName: "edp"
  platform: "openshift"
  database:
    host: edp-install-wizard-db
    name: edp-install-wizard-db
    port: 5432

name: reconciler
image:
  name: reconciler
  version: v2.5.0