global:
  # -- namespace or a project name (in case of OpenShift)
  edpName: ""
  # -- platform type that can be "kubernetes" or "openshift"
  platform: "openshift"
  database:
    # -- database host
    host: edp-db
    # -- database name
    name: edp-db
    # -- database port
    port: 5432

# -- component name
name: reconciler
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  # -- EDP reconciler Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/reconciler)
  repository: epamedp/reconciler
  # -- if not defined then .Chart.AppVersion is used
  # -- EDP reconciler Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/reconciler/tags)
  tag:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 32Mi
