apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "reconciler.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      serviceAccountName: edp-{{ .Values.name }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          command:
            - {{ .Values.name }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Values.name }}
            - name: PLATFORM_TYPE
              value: "{{ .Values.global.platform }}"
            - name: DB_HOST
              value: "{{ .Values.global.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.global.database.port }}"
            - name: DB_NAME
              value: "{{ .Values.global.database.name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-admin-console
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-admin-console
                  key: password
            - name: DB_SSL_MODE
              value: "disable"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
