{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "reconciler.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
rules:
  - apiGroups:
      - '*'
    resources:
      - gitservers
      - gitservers/status
      - gitservers/finalizers
      - cdpipelines
      - cdpipelines/finalizers
      - cdpipelines/status
      - codebases
      - codebases/status
      - codebases/finalizers
      - codebasebranches
      - codebasebranches/status
      - codebasebranches/finalizers
      - codebaseimagestreams
      - codebaseimagestreams/status
      - codebaseimagestreams/finalizers
      - jenkins
      - jenkins/finalizers
      - jenkins/status
      - jenkinses
      - jenkinses/finalizers
      - jenkinses/status
      - jenkinsserviceaccounts
      - jenkinsserviceaccounts/finalizers
      - jenkinsserviceaccounts/status
      - jenkinsjobs
      - jenkinsjobs/finalizers
      - jenkinsjobs/status
      - jenkinsserviceaccounts
      - jenkinsscripts
      - edpcomponents
      - stages
      - stages/finalizers
      - stages/status
      - jiraservers
      - jiraservers/finalizers
      - jiraservers/status
      - services
      - perfservers
      - perfservers/finalizers
      - perfservers/status
      - perfdatasourcejenkinses
      - perfdatasourcejenkinses/finalizers
      - perfdatasourcejenkinses/status
      - perfdatasourcesonars
      - perfdatasourcesonars/finalizers
      - perfdatasourcesonars/status
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  {{ end }}
