{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "reconciler.labels" . | nindent 4 }}
  name: {{ .Values.name }}-{{ .Values.global.edpName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edp-{{ .Values.name }}
  namespace: {{ .Values.global.edpName }}
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Values.global.edpName }}
{{- end -}}