{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "reconciler.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
roleRef:
  kind: Role
  name: edp-{{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Values.global.edpName }}
userNames:
  - system:serviceaccount:{{ .Values.global.edpName }}:edp-{{ .Values.name }}
groupNames: []
{{- end -}}